accounts/api/urls.py
from django.urls import path

from .views import (UserDetailApiView, UserContactApiView, 
                    UserContactsDetailApiView, UserAddressApiView, 
                    UserAddressDetailApiView)

urlpatterns = [
    path('user/<int:pk>/', UserDetailApiView.as_view(), name='user-detail-api'),
    path('user/contacts/', UserContactApiView.as_view(), name='user-contacts-api'),
    path('user/contacts/contact/<user_id>/', UserContactsDetailApiView.as_view(), name='user-contact-detail-api'),
    path('user/addresses/', UserAddressApiView.as_view(), name='user-addresses-api'),
    path('user/addresses/address/<address_id>/', UserAddressDetailApiView.as_view(), name='user-address-detail-api'),
]

accounts/urls.py
from django.urls import path

from . import views


urlpatterns = [
    path('account/', views.user_detail, name='user-detail'),
    path('account/<str:username>', views.user_detail, name='user-detail'),
    path('account/user-update/', views.user_update, name='user-update'),
    path('account/user-delete/', views.user_delete, name='user-delete'),
    
    path('account/user-contacts/', views.user_contacts, name='user-contacts'),
    path('account/user-contacts/contact/@<other_username>/save/', views.user_save_contact, name='user-save-contact'),
    path('account/user-contacts/contact/@<other_username>/update/', views.user_update_contact, name='user-update-contact'),
    path('account/user-contacts/contact/@<other_username>/delete/', views.user_delete_contact, name='user-delete-contact'),
    
    path('account/user-addresses/', views.user_addresses, name='user-addresses'),
    path('account/user-addresses/address/add/', views.user_address_add, name='address-add'),
    path('account/user-addresses/address/<id>/update/', views.user_address_update, name='address-update'),
    path('account/user-addresses/address/<id>/delete/', views.user_address_delete, name='address-delete'),
]

card/urls.py
from django.urls import path

from . import views


urlpatterns = [
    path('', views.card_detail, name='card-detail'),
    path('<slug:slug>/add/', views.add_to_card, name='add-to-card'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls.i18n import i18n_patterns

from rest_framework import permissions
from drf_yasg.views import get_schema_view
from drf_yasg import openapi

from auctions.views import auctions


schema_view = get_schema_view(
    openapi.Info(
        title="OnAuc API",
        default_version='v1',
        description="OnAuc is a Django-based online auction platform that offers a robust user experience with features such as user authentication, auction creation, bidding, and real-time chat.",
        contact=openapi.Contact(email="najmiddinovbahrom402@gmail.com"),
        license=openapi.License(name="MIT License"),
    ),
    public=True,
    permission_classes=(permissions.IsAuthenticatedOrReadOnly,),
)


api_urlpatterns = [
    path('api/v1/users/', include('accounts.api.urls')),
    path('api/v1/auctions/', include('auctions.api.urls')),
    path('api/v1/dashboard/', include('dashboard.api.urls')),
    path('api/v1/links/', include('link_generator.api.urls')),
    path('api/v1/cart/', include('card.api.urls')),
    path('api/v1/orders/', include('order.api.urls')),  
    
    path('swagger/', schema_view.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui'),
    path('redoc/', schema_view.with_ui('redoc', cache_timeout=0), name='schema-redoc'),
]


urlpatterns = [
    path('', auctions),
    path('admin/', admin.site.urls),
    path('ckeditor5/', include('django_ckeditor_5.urls')),
    path('accounts/', include('allauth.urls')),
    path('accounts/', include('accounts.urls')),
    path('auctions/', include('auctions.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('', include('link_generator.urls')),
    path('card/', include('card.urls')),
    path('orders/', include('order.urls')),
    path('payment/', include('payments.urls', namespace='payments')),
    path('i18n/', include('django.conf.urls.i18n')),
    path('rosetta/', include('rosetta.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += api_urlpatterns

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.templatetags.static import static
from django.utils.translation import gettext_lazy as _

from django_ckeditor_5.fields import CKEditor5Field
from django_countries.fields import CountryField 


USER_ACCOUNT_TYPE_CHOICES = (
    ('PB', _('PUBLIC')),
    ('PR', _('PRIVATE')),
)


def customuser_avatar_path (instance, filename):
    ext = filename.split('.')[-1]
    path = f'media/users/{instance.id}/images/avatars/avatar.{ext}'
    return path


class CustomUser(AbstractUser):
    type = models.CharField(_('Type'), max_length=2, choices=USER_ACCOUNT_TYPE_CHOICES, default='PB')
    first_name = models.CharField(_('First Name'), max_length=50)
    last_name = models.CharField(_('Last Name'), max_length=50)
    avatar = models.ImageField(_('Avatar'), upload_to=customuser_avatar_path, blank=True, null=True)
    description = CKEditor5Field(_('Description'), config_name='default')
    
    def __str__(self):
        return f'{self.username} | {self.type}'
    
    @property
    def get_avatar_url(self):
        return self.avatar.url if self.avatar else static('images/users/default-avatar.svg')


class Contact(models.Model):
    owner = models.ForeignKey(CustomUser, on_delete=models.CASCADE, related_name='contacts', verbose_name=_('Owner'))
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE, related_name='users_that_saved_me', verbose_name=_('User'))
    first_name = models.CharField(_('First Name'), max_length=50)
    last_name = models.CharField(_('Last Name'), max_length=50)


class Address(models.Model):
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE, verbose_name=_('User'))
    recipient_name = models.CharField(_('Recipient Name'), max_length=255)
    street_address = models.CharField(_('Street Address'), max_length=255)
    city = models.CharField(_('City'), max_length=255)
    state = models.CharField(_('State'), max_length=100)
    postal_code = models.CharField(_('Postal Code'), max_length=20)
    country = CountryField(verbose_name=_('Country'))
    phone_number = models.CharField(_('Phone Number'), max_length=20)
    email = models.EmailField(_('Email'), blank=True)
    instructions = models.TextField(_('Instructions'), blank=True)
    is_primary = models.BooleanField(_('Is Primary'), default=False)

    def __str__(self):
        return f"{self.recipient_name} - {self.street_address}, {self.city}, {self.country}"

    class Meta:
        verbose_name_plural = 'Addresses'

auctions/models.py
# TODO: link requests, that auction owner can accept for private and OC type of auctions

from django.db import models
from django.urls import reverse
from django.utils import timezone
from django.utils.translation import gettext_lazy as _

import uuid
from django_ckeditor_5.fields import CKEditor5Field

from labeler.models import Category, Tag
from accounts.models import CustomUser
from .validators import validate_video_file_extension


AUCTION_TYPE_CHOICES = (
    ('PB' , _('Public')),        # all users can see the auction
    ('PR' , _('Private')),       # only invited users can see the auction 
    ('OC', _('Only Contacts')),  # invited and owner's contacts can see the auction
)


def auction_image_path (instance, filename):
    ext = filename.split('.')[-1]
    path = f'media/auctions/{instance.id}/images/main_image.{ext}'
    return path


def auction_additional_image_path(instance, filename):
    ext = filename.split('.')[-1]
    path = f'media/auctions/{instance.id}/images/additional_image.{ext}'
    return path


def auction_additional_video_path(instance, filename):
    ext = filename.split('.')[-1]
    path = f'media/auctions/{instance.id}/videos/additional_video.{ext}'
    return path


def additional_field_icon_path(instance, filename):
    ext = filename.split('.')[-1]
    path = f'media/auctions/additional_fields/{instance.id}/icons/icon.{ext}'
    return path


class Auction(models.Model):
    id = models.UUIDField(_('Id'), primary_key=True, default=uuid.uuid4, editable=False)
    owner = models.ForeignKey(CustomUser, on_delete=models.CASCADE, related_name='auctions', verbose_name=_('Owner'))
    winner = models.ForeignKey(CustomUser, on_delete=models.SET_NULL, blank=True, null=True, related_name='winner', verbose_name=_('Winner'))
    main_image = models.ImageField(_('Main Image'), upload_to=auction_image_path)
    type = models.CharField(_('Type'), max_length=2, choices=AUCTION_TYPE_CHOICES, default='PB')
    title = models.CharField(_('Title'), max_length=60)
    slug = models.SlugField(_('Slug'), )
    summary = models.CharField(_('Summary'), max_length=200)
    description = CKEditor5Field(_('Description'), config_name='default')
    starter_price = models.PositiveIntegerField(_('Starter Price'), default=0)
    auction_price = models.PositiveIntegerField(_('Auction Price'), default=0)
    participants = models.ManyToManyField(CustomUser, through='ParticipantData', related_name='participanted_auctions', verbose_name=_('Participants'))
    user_watchers = models.ManyToManyField(CustomUser, through='Watchers', related_name='watched_auctions', verbose_name=_('User Watchers'))
    user_likes = models.ManyToManyField(CustomUser, through='Like', related_name='liked_auctions', verbose_name=_('User Likes'))
    
    active = models.BooleanField(_('Active'), default=False)
    start_time = models.DateTimeField(_('Start Time'), blank=True, null=True)
    end_time = models.DateTimeField(_('End Time'), )
    created = models.DateTimeField(_('Created'), auto_now_add=True)
    updated = models.DateTimeField(_('Updated'), auto_now=True)
    
    categories = models.ManyToManyField(Category, related_name='auction_categories', verbose_name=_('Categories'))
    tags = models.ManyToManyField(Tag, related_name='auction_tags', verbose_name=_('Tags'))
    
    permissions = models.ManyToManyField(CustomUser, through='AuctionUserPermission', verbose_name='Permissions')
    
    class Meta:
        ordering = ['-created', '-updated']
    
    def __str__(self):
        return self.title
    
    @property
    def get_absolute_url(self):
        if self.type == 'PB':
            return reverse('auction', args=[self.slug])
        return reverse('auction-private', args=[self.slug])
    
    @property
    def get_current_price(self):
        return self.starter_price if self.starter_price > self.auction_price else self.auction_price
    
    @property
    def get_main_image(self):
        return self.main_image.url
    
    @property
    def get_start_time(self):
        now = timezone.now()
        if self.start_time is None or self.start_time >= now:
            return True
        elif self.start_time < now:
            return False
    
    @property
    def get_end_time(self):
        now = timezone.now()
        if self.end_time is None or self.end_time >= now:
            return True
        elif self.end_time < now:
            return False
    
    @property
    def get_time_now(self):
        return timezone.now()
    

class ParticipantData(models.Model):
    '''
    Auction participants Through Table
    '''
    participant = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    auction = models.ForeignKey(Auction, on_delete=models.CASCADE)
    created = models.DateTimeField(auto_now_add=True)
    price = models.PositiveIntegerField(default=0)


class Watchers(models.Model):
    '''
    Auction user_watchers Through Table
    '''
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    auction = models.ForeignKey(Auction, on_delete=models.CASCADE)
    created = models.DateTimeField(auto_now_add=True)


class Like(models.Model):
    '''
    Auction user_likes Through Table
    '''
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    auction = models.ForeignKey(Auction, on_delete=models.CASCADE)
    created = models.DateTimeField(auto_now_add=True)


class AuctionUserPermission(models.Model):
    '''
    Auction User Permissions Through Table
    '''
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    auction = models.ForeignKey(Auction, on_delete=models.CASCADE)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    can_edit = models.BooleanField(default=False)
    can_delete = models.BooleanField(default=False)
    can_add_admin = models.BooleanField(default=False)


class ImageField(models.Model):
    '''
    Auction Additional Image Field
    '''
    id = models.UUIDField(_('Id'), primary_key=True, default=uuid.uuid4, editable=False)
    image = models.ImageField(_('Image'), upload_to=auction_additional_image_path)
    auction = models.ForeignKey(Auction, on_delete=models.CASCADE, related_name='image_fields', verbose_name=_('Auction'))
    
    created = models.DateTimeField(_('Created'), auto_now_add=True)
    updated = models.DateTimeField(_('Updated'), auto_now=True)


class VideoField(models.Model):
    '''
    Auction Video Field
    '''
    id = models.UUIDField(_('Id'), primary_key=True, default=uuid.uuid4, editable=False)
    video = models.FileField(_('Video'), upload_to=auction_additional_video_path, validators=[validate_video_file_extension])
    auction = models.ForeignKey(Auction, on_delete=models.CASCADE, related_name='video_fields', verbose_name=_('Auction'))
    
    created = models.DateTimeField(_('Created'), auto_now_add=True)
    updated = models.DateTimeField(_('Updated'), auto_now=True)


class AdditionalField(models.Model):
    '''
    Auction Additional Field
    '''
    id = models.UUIDField(_('Id'), primary_key=True, default=uuid.uuid4, editable=False)
    auction = models.ForeignKey(Auction, on_delete=models.CASCADE, related_name='additional_fields', verbose_name=_('Auction'))
    icon = models.ImageField(_('Icon'), upload_to=additional_field_icon_path)
    title = models.CharField(_('Title'), max_length=30)
    description = CKEditor5Field(_('Description'), config_name='default')
    
    created = models.DateTimeField(_('Created'), auto_now_add=True)
    updated = models.DateTimeField(_('UPdated'), auto_now=True)


class Message(models.Model):
    '''
    Auction Message model
    '''
    user = models.ForeignKey(CustomUser, on_delete=models.SET_NULL, blank=True, null=True, related_name='messages')
    auction = models.ForeignKey(Auction, on_delete=models.CASCADE, related_name='messages')
    text = models.CharField(max_length=250)
    
    created = models.DateTimeField(auto_now_add=True)


class Comment(models.Model):
    '''
    Auction Comment Model
    '''
    user = models.ForeignKey(CustomUser, on_delete=models.SET_NULL, blank=True, null=True, related_name='auction_comments')
    auction = models.ForeignKey(Auction, on_delete=models.CASCADE, related_name='comments')
    text = models.CharField(max_length=300)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    
    def __str__(self):
        return f'{self.text} {self.auction}'


class LocationData(models.Model):
    auction = models.ForeignKey(Auction, on_delete=models.CASCADE, related_name='users_locations')
    country = models.CharField(max_length=56)
    city = models.CharField(max_length=85)
    ip_address = models.CharField(max_length=30)

order/models.py
from django.db import models
from django.utils.translation import gettext_lazy as _

from auctions.models import Auction
from accounts.models import CustomUser, Address


ORDER_PAYMENT_CHOICES = (
    ('ST', 'STRIPE'),
)


class Order(models.Model):
    user = models.ForeignKey(CustomUser, on_delete=models.PROTECT, verbose_name=_('User'))
    address = models.ForeignKey(Address, on_delete=models.PROTECT, verbose_name=_('Address'))
    total_amount = models.DecimalField(_('Total Amount'), max_digits=10, decimal_places=2)
    delivered = models.BooleanField(_('Delivered'), default=False)
    paid = models.BooleanField(_('Paid'), default=False)
    payment_method = models.CharField(_('Payment Method'), max_length=2, choices=ORDER_PAYMENT_CHOICES)


class OrderItem(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    product = models.ForeignKey(Auction, on_delete=models.CASCADE)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    

accounts/forms.py
from django import forms
from django.utils.translation import gettext_lazy as _

from allauth.account.forms import SignupForm
from django_ckeditor_5.widgets import CKEditor5Widget

from .models import CustomUser, Address


class UserUpdateForm(forms.ModelForm):
    class Meta:
        model = CustomUser
        fields = ('avatar', 'username', 'email', 'first_name', 'last_name', 'description',)
        widgets = {
            'description': CKEditor5Widget(
                attrs={'class': 'django_ckeditor_5'}, config_name='default'
            ),
        }


class AddressForm(forms.ModelForm):
    class Meta: 
        model = Address
        fields = ['recipient_name', 'street_address', 'city', 'state', 'postal_code', 'country', 'phone_number', 'email', 'instructions', 'is_primary']


class CustomSignupForm(SignupForm):
    first_name = forms.CharField(max_length=30, label=_('First Name'))
    last_name = forms.CharField(max_length=30, label=_('Last Name'))
    
    def save(self, request):
        user = super(CustomSignupForm, self).save(request)
        user.first_name = self.cleaned_data['first_name']
        user.last_name = self.cleaned_data['last_name']
        user.save()
        return user

accounts/templates/accounts/user-address-create-update.html
{% extends 'base.html' %}
{% load i18n %}
{% block title %}{% trans 'Address Form' %}{% endblock title %}

{% block content %}
<section class="user-update">
    {% if form.errors %}
    <div class="alert alert-danger">
        {% trans 'Please correct the error below.' %}
    </div>
    {% endif %}
    
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <h2 class="form-header">{% trans 'Address Form' %}</h2>
        <div class="form-body">
            {% for field in form %}
            <div class="form-control">
                {{ field.label_tag }}
                {{ field }}
                {{ field.errors }}
            </div>
            {% endfor %}
            <a href="{% url 'user-addresses' %}" class="btn btn-secondary">{% trans 'Cancel' %}</a>
            <button type="submit" class="btn btn-primary">{% trans 'Save' %}</button>
        </div>
    </form>
</section>
{% endblock content %}

accounts/templates/accounts/user-addresses.html
{% extends 'base.html' %}
{% load i18n %}
{% block title %}
{% trans 'Your Addresses' %}
{% endblock title %}

{% block content %}
<section class="addresses-list">
    <div class="btn-group" style="margin-bottom: 1rem;">
        <a class="btn" href="{% url 'address-add' %}">{% trans 'Add New Address' %}</a>
    </div>
    {% for address in user_addresses %}
    <div>
        <div class="address-item">
            <div class="address-details">
                <h2>{{ address.recipient_name }}</h2>
                <p>{{ address.street_address }}</p>
                <p>{{ address.city }}, {{ address.state }} {{ address.postal_code }}</p>
            </div>
            <div class="btn-group">
                <a class="btn" href="{% url 'address-update' address.id %}">{% trans 'Edit' %}</a>
                <a class="btn" href="{% url 'address-delete' address.id %}">{% trans 'Delete' %}</a>
            </div>
        </div>
    </div>
    {% endfor %}
</section>
{% endblock content %}

accounts/templates/accounts/user-contact-update-create.html
{% extends 'base.html' %}
{% load i18n %}
{% block title %}{% trans 'Contact' %}{% endblock title %}

{% block content %}
<section class="user-contact-e-c">
    <form method="POST">
        {% csrf_token %}
        <h2 class="form-header">{% trans 'Contact' %}</h2>
        <div class="form-body">
            <div class="form-control">
                <label for="contact-first-name">{% trans 'First Name:' %}</label>
                <input type="text" id="contact-first-name" value="{{ contact.first_name }}" name="contact_first_name" required>
            </div>
            <div class="form-control">
                <label for="contact-last-name">{% trans 'Last Name:' %}</label>
                <input type="text" id="contact-last-name" value="{{ contact.last_name }}" name="contact_last_name">
            </div>
        </div>
        <button class="btn" type="submit">{% trans 'Save' %}</button>
    </form>
</section>
{% endblock content %}

accounts/templates/accounts/user-contacts.html
{% extends 'base.html' %}
{% load i18n %}
{% block title %}{% trans 'Contacts' %}{% endblock title %}

{% block content %}
<!-- user detail section -->
<section class="user-detail">
    {% if user_contacts %}
    {% for user_contact in user_contacts %}
    <div class="single-user" style="display: flex; flex-direction: row; border-bottom: 1px solid black; margin-bottom: .5rem;">
        <div class="user-avatar">
            <img src="{{ user_contact.user.get_avatar_url }}" alt="Avatar">
        </div>
        <div class="user-info" style="margin-left: 20px; text-align: left;">
            <h2>{{ user_contact.first_name }} {{ user_contact.last_name }}</h2>
            <p>{% trans 'Email:' %} {{ user_contact.user.email }}</p>
            <div class="btn-group">
                <a href="{% url 'user-update-contact' user_contact.user.username %}" class="btn btn-primary">{% trans 'Edit Contact' %}</a>
                <a href="{% url 'user-delete-contact' user_contact.user.username %}" class="btn">{% trans 'Delete Contact' %}</a>
            </div>
        </div>
    </div>
    {% endfor %}
    {% else %}
    <h1>{% trans "You haven't saved contacts yet..." %}</h1>
    {% endif %}
</section>
<!-- end of user detail section -->
{% endblock content %}

accounts/templates/accounts/user-detail.html
{% extends 'base.html' %}
{% load i18n %}
{% load static %}

{% block title %}{% trans 'User Detail' %}{% endblock title %}

{% block style %}
<link rel="stylesheet" href="{% static 'css/dashboard.css' %}">
{% endblock style %}

{% block content %}
<!-- user detail section -->
<section class="user-detail">
    <div class="user-avatar">
        <img src="{{ user.get_avatar_url }}" alt="Avatar">
    </div>
    <div class="user-info">
        {% if user_contact %}
        <h2>{{ user_contact.first_name }} {{ user.last_name }}</h2>
        {% else %}
        <h2>{{ user.first_name }} {{ user.last_name }}</h2>
        {% endif %}
        <p>{% trans 'Email:' %} {{ user.email }}</p>
        {% if user in request.user.contacts.all %}
        <p class="contact-status">{% trans 'Saved as contact' %}</p>
        {% endif %}
        <div class="description">
            {{ user.description|safe }}
        </div>
        <div class="btn-group">
            {% if request.user == user %}
            <a href="{% url 'user-update' %}" class="btn btn-primary">{% trans "Edit Profile" %}</a>
            <a href="{% url 'user-contacts' %}" class="btn btn-primary">{% trans "Contacts" %}</a>
            <a href="{% url 'user-delete' %}" class="btn btn-secondary">{% trans "Delete Account" %}</a>
            {% endif %}
            {% if not user_contact and request.user != user %}
            <a class="btn" href="{% url 'user-save-contact' user.username %}">{% trans "Save As A contact" %}</a>
            {% elif user_contact %}
            <a class="btn" href="{% url 'user-update-contact' user.username %}">{% trans "Edit Contact" %}</a>
            {% endif %}
        </div>
    </div>
    {% if request.user == user %}
    <div class="user-data" style="margin-top: 4rem">
        <div class="orders">
            <h2 class="title" style="margin-bottom: 1rem">{% trans "Your Orders" %}</h2>
            <table class="user-auctions">
                <tr>
                    <th>{% trans "Id" %}</th>
                    <th>{% trans "Title" %}</th>
                    <th>{% trans "Paid" %}</th>
                    <th>{% trans "Delivered" %}</th>
                </tr>
                {% for order in request.user.order_set.all %}
                <tr>
                    <td>{{ order.id }}</td>
                    <td>
                        <a href="{% url 'order-data' order.id %}">{{ order.address.city }}</a>
                    </td>
                    <td>{{ order.paid }}</td>
                    <td>{{ order.delivered }}</td>
                </tr>
                {% endfor %}
            </table>
        </div>
    </div>

    <div class="dashboard-list">
        <h1 class="title" style="margin-bottom: 1rem;">{% trans "Auctions that You participanted" %}</h1>
        {% if request.user.participantdata_set.exists %}
        <table class="user-auctions">
            <tr>
                <th>{% trans "Image" %}</th>
                <th>{% trans "Title" %}</th>
                <th>{% trans "Participants" %}</th>
                <th>{% trans "Current Price" %}</th>
                <th>{% trans "End Time" %}</th>
                <th>{% trans "Your Bid" %}</th>
            </tr>
            {% for data in request.user.participantdata_set.all %}
            {% with auction=data.auction %}
            <tr class="user-auction">
                <td class="user-auction-image">
                    <img src="{{ auction.get_main_image }}" alt="{{ auction.title }}">
                </td>
                <td>
                    <a href="{% url 'auction' auction.slug %}">{{ auction.title }}</a>
                </td>
                <td>
                    <p>{{ auction.participants.count }}</p>
                </td>
                <td>
                    <p>${{ auction.get_current_price }}</p>
                </td>
                <td>{{ auction.end_time }}</td>
                <td>${{ data.price }}</td>
            </tr>
            {% endwith %}
            {% endfor %}
        </table>
        {% else %}
        <h3>{% trans "No auctions found." %}</h3>
        {% endif %}
    </div>

    <div class="dashboard-list">
        <h1 class="title" style="margin-bottom: 1rem;">{% trans "Auctions that You Winned" %}</h1>
        {% if request.user.winner.all %}
        <table class="user-auctions">
            <tr>
                <th>{% trans "Image" %}</th>
                <th>{% trans "Title" %}</th>
                <th>{% trans "Participants" %}</th>
                <th>{% trans "End Time" %}</th>
                <th>{% trans "Your Bid" %}</th>
            </tr>
            {% for auction in request.user.winner.all %}
            <tr class="user-auction">
                <td class="user-auction-image">
                    <img src="{{ auction.get_main_image }}" alt="{{ auction.title }}">
                </td>
                <td>
                    <a href="{% url 'auction' auction.slug %}">{{ auction.title }}</a>
                </td>
                <td>
                    <p>{{ auction.participants.count }}</p>
                </td>
                <td>{{ auction.end_time }}</td> 
                <td>${{ auction.get_current_price }}</td>
            </tr>
            {% endfor %}
        </table>
        {% else %}
        <h3>{% trans "No auctions found." %}</h3>
        {% endif %}
    </div>
    {% endif %}
</section>
<!-- end of user detail section -->
{% endblock content %}

accounts/templates/accounts/user-update.html
{% extends 'base.html' %}
{% load i18n %}
{% block title %}{% trans 'Update User' %}{% endblock title %}

{% block header %}
{{ form.media }}
{% endblock header %}

{% block content %}
<section class="user-update">
    {% if form.errors %}
    <div class="alert alert-danger">
        Please correct the error below.
    </div>
    {% endif %}
    
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <h2 class="form-header">Update User Details</h2>
        <div class="form-body">
            {% for field in form %}
            <div class="form-control">
                {{ field.label_tag }}
                {{ field }}
                {{ field.errors }}
            </div>
            {% endfor %}
            <a href="{% url 'user-detail' user.id %}" class="btn btn-secondary">Cancel</a>
            <button type="submit" class="btn btn-primary">Update</button>
        </div>
    </form>


    {% if user.is_superuser %}
    {% comment %} <a href="{% url 'user-list' %}" class="btn btn-light">View All Users</a> {% endcomment %}
    {% endif %}

    {% comment %} <a href="{% url 'password-change' %}" class="btn btn-light">Change Password</a> {% endcomment %}

    {% comment %} <a href="{% url 'user-delete' user.id %}" class="btn btn-danger">Delete User</a> {% endcomment %}

    {% comment %} <a href="{% url 'user-activate' user.id %}" class="btn btn-success">Activate User</a> {% endcomment %}
</section>
{% endblock content %}