card/urls.py
from django.urls import path

from . import views


urlpatterns = [
    path('', views.card_detail, name='card-detail'),
    path('<slug:slug>/add/', views.add_to_card, name='add-to-card'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls.i18n import i18n_patterns

from rest_framework import permissions
from drf_yasg.views import get_schema_view
from drf_yasg import openapi

from auctions.views import auctions


schema_view = get_schema_view(
    openapi.Info(
        title="OnAuc API",
        default_version='v1',
        description="OnAuc is a Django-based online auction platform that offers a robust user experience with features such as user authentication, auction creation, bidding, and real-time chat.",
        contact=openapi.Contact(email="najmiddinovbahrom402@gmail.com"),
        license=openapi.License(name="MIT License"),
    ),
    public=True,
    permission_classes=(permissions.IsAuthenticatedOrReadOnly,),
)


api_urlpatterns = [
    path('api/v1/users/', include('accounts.api.urls')),
    path('api/v1/auctions/', include('auctions.api.urls')),
    path('api/v1/dashboard/', include('dashboard.api.urls')),
    path('api/v1/links/', include('link_generator.api.urls')),
    path('api/v1/cart/', include('card.api.urls')),
    path('api/v1/orders/', include('order.api.urls')),  
    
    path('swagger/', schema_view.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui'),
    path('redoc/', schema_view.with_ui('redoc', cache_timeout=0), name='schema-redoc'),
]


urlpatterns = [
    path('', auctions),
    path('admin/', admin.site.urls),
    path('ckeditor5/', include('django_ckeditor_5.urls')),
    path('accounts/', include('allauth.urls')),
    path('accounts/', include('accounts.urls')),
    path('auctions/', include('auctions.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('', include('link_generator.urls')),
    path('card/', include('card.urls')),
    path('orders/', include('order.urls')),
    path('payment/', include('payments.urls', namespace='payments')),
    path('i18n/', include('django.conf.urls.i18n')),
    path('rosetta/', include('rosetta.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += api_urlpatterns

order/api/urls.py
from django.urls import path

from . import views


urlpatterns = [
    path('order/checkout/', views.checkout, name='checkout-api'),
    path('order/', views.order_data, name='order-data-api'),
    path('order/data/<order_id>/', views.order_data, name='order-data-api'),
]

order/urls.py
from django.urls import path

from . import views


urlpatterns = [
    path('order/checkout/', views.checkout, name='checkout'),
    path('order/order-data/', views.order_data, name='order-data'),
    path('order/order-data/<order_id>', views.order_data, name='order-data'),
]

payments/urls.py
from django.urls import path

from . import views


app_name='payments'

urlpatterns = [
    path('success/', views.success, name='success'),
    path('cancel/', views.cancel, name='cancel'),
    path('stripe/<order_id>', views.create_checkout_session, name='stripe'),
    path('stripe/webhook/', views.stripe_webhook, name='stripe_webhook'),
]

order/models.py
from django.db import models
from django.utils.translation import gettext_lazy as _

from auctions.models import Auction
from accounts.models import CustomUser, Address


ORDER_PAYMENT_CHOICES = (
    ('ST', 'STRIPE'),
)


class Order(models.Model):
    user = models.ForeignKey(CustomUser, on_delete=models.PROTECT, verbose_name=_('User'))
    address = models.ForeignKey(Address, on_delete=models.PROTECT, verbose_name=_('Address'))
    total_amount = models.DecimalField(_('Total Amount'), max_digits=10, decimal_places=2)
    delivered = models.BooleanField(_('Delivered'), default=False)
    paid = models.BooleanField(_('Paid'), default=False)
    payment_method = models.CharField(_('Payment Method'), max_length=2, choices=ORDER_PAYMENT_CHOICES)


class OrderItem(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    product = models.ForeignKey(Auction, on_delete=models.CASCADE)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    

order/api/views.py
from django.shortcuts import get_object_or_404

from rest_framework.response import Response
from rest_framework.decorators import api_view

from order.models import Order, OrderItem
from .serializers import OrderSerializer, OrderItemSerializer
from accounts.api.serializers import AddressSerializer
from card.api.serializers import CartItemSerializer


@api_view(['GET'])
def checkout(request):
    saved_addresses = request.user.address_set.all()
    card_items = request.user.cards.last().items.all()
    
    if not card_item.exists():
        return Response({'info': 'cart cannot be empty'}, status=405)
    
    total_count = 0
    total_price = 0
    for card_item in card_items:
        auction = card_item.auction
        # check user if the winner of the auction
        if auction.winner != request.user or auction.orderitem_set.exists():
            return Response('You are winner or already ordered item!', status=403)
            
        total_price += auction.get_current_price
        total_count += 1
    
    all_numbers = {
        'total_items': total_count,
        'total_price': total_price,
    }
    
    data = {
        'savedAddresses': AddressSerializer(saved_addresses, many=True).data,
        'card_items': CartItemSerializer(card_items, many=True).data,
        'all_numbers': all_numbers,
    }
    
    return Response(data)


@api_view(['GET'])
def order_data(request, order_id=None):
    user = request.user
    
    # get order data
    if order_id:
        order = get_object_or_404(user.order_set, pk=order_id)
    # create new order
    else:
        card_items = user.cards.last().items.all()
        
        payment_method = request.GET.get('payment-radio', None)
        address_id = request.GET.get('address-radio', None)
        
        if payment_method is None:
            return Response('Payment method is required!', status=400)
        
        if address_id is None:
            return Response('Address is required!', status=400)
        
        address = get_object_or_404(user.address_set, pk=address_id)
        
        total_price = 0
        order = Order.objects.create(user=user, payment_method=payment_method, address=address, total_amount=0)
        for card_item in card_items:
            OrderItem.objects.create(order=order, product=card_item.auction, price=card_item.auction.get_current_price)
            total_price += card_item.auction.get_current_price
            card_item.delete()
        
        order.total_amount = total_price
        order.save()
    
    data = {
        'order': OrderSerializer(order, many=False),
        'order_items': OrderItemSerializer(order.orderitem_set.all(), many=True),
    }
        
    return Response(data)

order/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse

from accounts.forms import AddressForm
from .models import Order, OrderItem


@login_required
def checkout(request):
    saved_addresses = request.user.address_set.all()
    new_address = AddressForm()
    card_items = request.user.cards.last().items.all()
    
    if not card_items.exists():
        return redirect('card-detail')
    
    total_count = 0
    total_price = 0
    for card_item in card_items:
        auction = card_item.auction
        # check user if the winner of the auction
        if auction.winner != request.user or auction.orderitem_set.exists():
            return render(request, 'order/not_allowed.html')
            
        total_price += auction.get_current_price
        total_count += 1
    
    all_numbers = {
        'total_items': total_count,
        'total_price': total_price,
    }
    
    context = {
        'saved_addresses': saved_addresses,
        'new_address': new_address,
        'card_items': card_items,
        'all_numbers': all_numbers,
    }
    
    return render(request, 'order/checkout.html', context)


@login_required
def order_data(request, order_id=None):
    user = request.user
    
    # get order data
    if order_id:
        order = get_object_or_404(user.order_set, pk=order_id)
    # create new order
    else:
        card_items = user.cards.last().items.all()
        
        payment_method = request.POST.get('payment-radio')
        
        address_id = request.POST.get('address-radio')
        
        if address_id == 'new_address':
            new_address = AddressForm(request.POST)
            if new_address.is_valid():
                address = new_address.save(commit=False)
                address.user = user
                address.save()
            else:
                return render(request, 'order/checkout.html', {'new_address': new_address})
        else:
            address = get_object_or_404(user.address_set, pk=address_id)
        
        total_price = 0
        order = Order.objects.create(user=user, payment_method=payment_method, address=address, total_amount=0)
        for card_item in card_items:
            OrderItem.objects.create(order=order, product=card_item.auction, price=card_item.auction.get_current_price)
            total_price += card_item.auction.get_current_price
            card_item.delete()
        
        order.total_amount = total_price
        order.save()
    
    context = {
        'order': order,
        'order_items': order.orderitem_set.all(),
    }
        
    return render(request, 'order/order-data.html', context)

order/templates/order/checkout.html
{% extends 'base.html' %}

{% load i18n %}
{% load static %}

{% block title %}
{% trans "Checkout" %}
{% endblock title %}

{% block style %}
<link rel="stylesheet" href="{% static 'css/dashboard.css' %}">
<link rel="stylesheet" href="{% static 'css/checkout.css' %}">
{% endblock style %}

{% block content %}
<form class="checkout checkout-main-form" method="POST" action="{% url 'order-data' %}">
    {% csrf_token %}
    <div class="payment-list">
        <h1>{% trans "Select Payment Method" %}</h1>
        <div>
            <input type="radio" name="payment-radio" required value='ST'>{% trans "Stripe" %}
        </div>
    </div>
    
    <div class="address-list">
        <h1>{% trans "Select Address" %}</h1>
        {% for saved_adress in saved_addresses %}
        <div class="address-list">
            <label class="address-info">
                <input type="radio" name="address-radio" required value={{ saved_adress.id }}>
                {% with address=saved_adress %}
                <h4 style="display: inline-block;">{{ address.recipient_name }}</h3>
                <p>{{ address.street_address }}</p>
                {% endwith %}
            </a>
        </div>
        {% endfor %}
        <label>
            <input type="radio" name="address-radio" required id="new-address" value="new_address">{% trans "New Address" %}

            <div action="" class="checkout-form">
                <div class="form-body">
                    {% for field in new_address %}
                    <div class="form-control">
                        {{ field.label_tag }}
                        {{ field }}
                        {{ field.errors }}
                    </div>
                    {% endfor %}
                </div>
            </div>
        </label>
    </div>
    
    <div class="dashboard-list">
        <h1 class="title">{% trans "Your Auctions" %}</h1>
        <table class="user-auctions">
            <tr>
                <th>{% trans "Image" %}</th>
                <th>{% trans "Title" %}</th>
                <th>{% trans "Price" %}</th>
            </tr>
            {% for card_item in card_items %}
            <tr class="user-auction">
                <td class="user-auction-image">
                    <img src="{{ card_item.auction.get_main_image }}" alt="{{ card_item.auction.title }}">
                </td>
                <td>
                    <a href="{% url 'dashboard-auction-detail' card_item.auction.slug %}">{{ card_item.auction.title }}</a>
                </td>
                <td>
                    <p>${{ card_item.auction.get_current_price }}</p>
                </td>
            </tr>
            {% endfor %}
        </table>
    </div>
    
    <div class="btn-group">
        <button type="submit" class="btn">{% trans "Place Order" %}</button>
    </div>
</form>
{% endblock content %}

{% block script %}
    <script>
        const formElements = document.querySelectorAll('.form-control input, .form-control select');
        formElements.forEach(element => {
            element.removeAttribute('required');
        });
    </script>
{% endblock %}

order/templates/order/not_allowed.html
{% extends 'base.html' %}
{% load i18n %}
{% block title %}
{% trans "Not Allowed" %}
{% endblock title %}

{% block content %}
<h1>{% trans "Before order, you should be the winner of auction!" %}</h1>
{% endblock content %}

order/templates/order/order-data.html
{% extends 'base.html' %}

{% load i18n %}
{% load static %}

{% block title %}
{% trans "Order" %}
{% endblock title %}

{% block style %}
<link rel="stylesheet" href="{% static 'css/dashboard.css' %}">
<link rel="stylesheet" href="{% static 'css/checkout.css' %}">
{% endblock style %}

{% block content %}
<section class="checkout">
    <div class="payment-list">
        <div class="all-numbers">
            <div class="number-box">
                <p>{% trans "Total Price" %}</p>
                <span>{{ order.total_amount }}</span>
            </div>
            <div class="number-box">
                <p>{% trans "Payment Method" %}</p>
                <span>{{ order.payment_method }}</span>
            </div>
            <div class="number-box">
                <p>{% trans "Payment Status" %}</p>
                <span>{{ order.paid }}</span>
            </div>
            <div class="number-box">
                <p>{% trans "Order ID" %}</p>
                <span>{{ order.id }}</span>
            </div>
            <div class="number-box">
                <p>{% trans "Payment Confirmation" %}</p>
                <span>{% trans "You will receive a confirmation email shortly." %}</span>
            </div>
        </div>
    </div>
    
    <div class="address-list">
        <h1>{% trans "Shipping Address" %}</h1>
        <a href="" class="address-info">
            {% with address=order.address %}
            <h4>{{ address.recipient_name }}</h3>
            <p>{{ address.street_address }}</p>
            {% endwith %}
        </a>
    </div>
    
    <div class="dashboard-list">
        <h1 class="title">{% trans "Your Auctions" %}</h1>
        <table class="user-auctions">
            <tr>
                <th>{% trans "Image" %}</th>
                <th>{% trans "Title" %}</th>
                <th>{% trans "Price" %}</th>
            </tr>
            {% for order_item in order_items %}
            <tr class="user-auction">
                <td class="user-auction-image">
                    <img src="{{ order_item.product.get_main_image }}" alt="{{ order_item.product.title }}">
                </td>
                <td>
                    <a href="{% url 'auction' order_item.product.slug %}">{{ order_item.product.title }}</a>
                </td>
                <td>
                    <p>${{ order_item.price }}</p>
                </td>
            </tr>
            {% endfor %}
        </table>
    </div>

    {% if not order.paid %}
    <div class="btn-group">
        <a href="{% url 'payments:stripe' order.id %}" class="btn">{% trans "Pay Now" %}</a>
    </div>
    {% endif %}
</section>
{% endblock content %}